### ISSUE TITLE
Access example server from different URL

### ISSUE THREAD

**Issue by Mikekij** [Yubico/python-u2flib-server#13]
I'd like a stand-alone application (running at https://localhost:8000) to be able to prompt users for a U2F authentication against this example server (running at https://localhost:8081). I keep getting ERR_CONNECTION_REFUSED errors when making the initial registrationRequest.

Is there a way to add a allow-cross-origin whitelist of URLs able to access this?

**Comment by dainnilsson** [comment]
What is giving you this error? The example server doesn't care where the request is coming from (in fact, it doesn't even know).

**Comment by Mikekij** [comment]
Sorry @dainnilsson ; I didn't catch that the "data" in "#{data}" was being defined by a call in another script. Got this all working. 

Thanks for the example server!
