### ISSUE TITLE
Openssl / M2Crypt -> Exception: Attestation signature verification failed!

### ISSUE THREAD

**Issue by Mikekij** [Yubico/python-u2flib-server#14]
I'm attempting to use this library in a Django app. I'm successfully able to generate a challenge and get a response from the U2F device. However, when I attempt to call u2f.complete_register(request,response) I'm getting an Attestation signature verification failed! error. 

Python 2.7
Django 1.7
M2Crypto 0.22.3
Openssl 1.0.2d_1
OS X 10.10.3

Request data:

    {"challenge": "SohCJaPJvuPZpobbeU7KWSQl8V6qkD_MLkLzbP0ZbJI","version":"U2F_V2","appId":"https://dev.myapp.com:8000"}

Response data: 

    {"registrationData":"BQRLFW_LoxzZF6ruTXs43dTiG4R10crtWTznY2Nf2KWZzr8QHVRNJArQ2a-LsKxHldwpaMtifK8-NPBSIWKyOH2pQG70Vg0yr5WPQPvUA_T7tMwKp5-mbANWjohFJBBJVeoom6VODrwooE87NVvH0VPbANnapY2bWTfDviyidCWUvKswggItMIIBF6ADAgECAgQFtgV5MAsGCSqGSIb3DQEBCzAuMSwwKgYDVQQDEyNZdWJpY28gVTJGIFJvb3QgQ0EgU2VyaWFsIDQ1NzIwMDYzMTAgFw0xNDA4MDEwMDAwMDBaGA8yMDUwMDkwNDAwMDAwMFowKDEmMCQGA1UEAwwdWXViaWNvIFUyRiBFRSBTZXJpYWwgOTU4MTUwMzMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAT9uN6zoe1w62NsBm62AGmWpflw_LXbiPw7MF1B5ZZvDBtUuFL-8KCQftF_O__CnU0yG5z4qEos6qA4yr011ZjeoyYwJDAiBgkrBgEEAYLECgIEFTEuMy42LjEuNC4xLjQxNDgyLjEuMTALBgkqhkiG9w0BAQsDggEBAH7T-2zMJSAT-C8hjCo32mAx0g5_MIHa_K6xKPx_myM5FL-2TWE18XziIfp2T0U-8Sc6jOlllWRCuy8eR0g_c33LyYtYU3f-9QsnDgKJ-IQ28a3PSbJiHuXjAt9VW5q3QnLgafkYFJs97E8SIosQwPiN42r1inS7RCuFrgBTZL2mcCBY_B8th5tTARHqYOhsY_F_pZRMyD8KommEiz7jiKbAnmsFlT_LuPR-g6J-AHKmPDKtZIZOkm1xEvoZl_eDllb7syvo94idDwFFUZonr92ORrBMpCkNhUC2NLiGFh51iMhimdzdZDXRZ4o6bwp0gpxN0_cMNSTR3fFteK3SG2QwRgIhAJi7YVdZbsMDY-r03vPUSOj3hOXp4kx1m3xBoC9HVbXXAiEAsh1SpVIMlLxFfBXIKKX3YDI9fSWudP5UcglZyU-A4JE","challenge":"SohCJaPJvuPZpobbeU7KWSQl8V6qkD_MLkLzbP0ZbJI","version":"U2F_V2","appId":"https://dev.medcrypt.com:8000","clientData":"eyJ0eXAiOiJuYXZpZ2F0b3IuaWQuZmluaXNoRW5yb2xsbWVudCIsImNoYWxsZW5nZSI6IlNvaENKYVBKdnVQWnBvYmJlVTdLV1NRbDhWNnFrRF9NTGtMemJQMFpiSkkiLCJvcmlnaW4iOiJodHRwczovL2Rldi5tZWRjcnlwdC5jb206ODAwMCIsImNpZF9wdWJrZXkiOiIifQ"}

Any suggestions?

**Comment by Mikekij** [comment]
FYI I attempted to follow the instructions to manually build and install openssl here:
https://github.com/gavinwahl/django-u2f/issues/4
But I still have the same issue.

**Comment by Mikekij** [comment]
One more interesting tidbit: Running the same app on a RaspberryPi (running Raspbian) with all of the same versions of the dependencies listed above works perfectly. 

Is there some other dependency I need to be checking the version of?

**Comment by Mikekij** [comment]
One more update: Found that M2Crypto won't build on OS X with openssl v > 0.9.8. It builds successfully on Raspbian with openssl v1.0.1e.

**Comment by Mikekij** [comment]
I found a (non-secure) work-around on OS X. By commenting out lines 95 and 96 of the verify_csr_signature function in u2f_v2.py, the authentication works. This is not a fix that would work in production, but does identify where the problem lies.

        def verify_csr_signature(self):
        data = chr(0x00) + self.app_param + self.chal_param + \
            self.key_handle + self.pub_key
        pubkey = self.certificate.get_pubkey()
        pubkey.reset_context('sha256')
        pubkey.verify_init()
        pubkey.verify_update(data)
        #if not pubkey.verify_final(self.signature) == 1:
            #raise Exception('Attestation signature verification failed!')

**Comment by dainnilsson** [comment]
My guess is that you're still using an M2Crypto that is linked against OpenSSL 0.9.8, which seems to not do the signature verification correctly. Unfortunately I don't have any pointers for getting building M2Crypto against the newer version on OS X.

**Comment by Mikekij** [comment]
@dainnilsson Unfortunately I'm now experiencing this same issue on Raspbian, using OpenSSL 1.0.1e. I'm also certain that I'm running 1.0.1d on OS X.

**Comment by zollman** [comment]
@Mikekij How certain are you, really? Because I installed openssl 1.0.x through brew, but it turns out cryptography was still linking against openssl 0.9.8 (the default install on OSX). Test with the following

```python
import cryptography.hazmat.backends

multi_backend=cryptography.hazmat.backends.default_backend()
ossl_be=multi_backent._backends[1]
print ossl_be.openssl_version_text()
```

If that says you're running 0.9.8, you need to clean out your virtualenv/lib directory and reinstall with:

Then reinstall with: `env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" python setup.py install`

(I tried just reinstalling cryptography and it didn't work)

**Comment by dainnilsson** [comment]
I'm closing this now, as the library now uses cryptography, so the original issue isn't likely to be applicable. If there is an issue with getting the correct version of OpenSSL to be used on OSX, then feel free to open a new issue about it.
