### ISSUE TITLE
Hard-coded Yubico products in u2f_v2.py

### ISSUE THREAD

**Issue by vcarel** [Yubico/python-u2flib-server#15]
I'm planning to use u2f_v2.py, but i'm concerned about hard-coded Yubico products:

```
FIXSIG = [
    'CN=Yubico U2F EE Serial 776137165',
    'CN=Yubico U2F EE Serial 1086591525',
    'CN=Yubico U2F EE Serial 1973679733',
    'CN=Yubico U2F EE Serial 13503277888',
    'CN=Yubico U2F EE Serial 13831167861',
    'CN=Yubico U2F EE Serial 14803321578'
]
```

What does it mean ? Where those serial come from and what is wrong with their X509 certificates ?

**Comment by dainnilsson** [comment]
Some of the early batches of U2F devices had attestation certificates that used a slightly sloppy way of encoding the signatures (signed by the CA). Newer versions of openssl are more strict about this encoding, and would fail signature verification for these. The actual signature data is correct, and this poses absolutely no security threat, but as this library uses openssl we have this hardcoded list of certificates that we "fix" before letting openssl verify them. You can see this code here: https://github.com/Yubico/python-u2flib-server/blob/2e9fca41c850374370255e92d29f1540dfdfbb98/u2flib_server/u2f_v2.py#L101

The certificate is serialized, a single byte is set to 0, then the certificate is parsed again. The byte in question is part of the encoding of the signature, that defines the number of unused bits, which openssl requires to be zero.

**Comment by vcarel** [comment]
Thanks, that's clear :-)
