### ISSUE TITLE
Remove dependency on pyasn1

### ISSUE THREAD

**Issue by moreati** [Yubico/python-u2flib-server#19]
python-u2flib-server uses pyasn1 for a single purpose - to implement `get_ext_by_oid()`.
The recent release of cryptography 1.2 fixes pyca/cryptography#2288 this can be achieved with `Certificate.extensions.get_extension_for_oid()`.

However, `get_ext_by_oid()` and `ExtensionMatcher` are implemented around comparing the raw bytes of the extension and cryptography only exposes these when the oid is of an `UnrecognizedExtension`. In general the cryptography ethos strongly discourages exposing raw bytes.

Should we take this opportunity to change the return type of `get_ext_by_oid()`?

**Comment by dainnilsson** [comment]
I agree that relying on UnrecognizedExtension isn't very elegant. What would you suggest changing the return type to? There are really two different functions that need to be able to read out extensions from the certificate. The first is for metadata matching, where an arbitrary OID can be given, and a binary value to match the extensions value against. The second is the transport hints extension defined in the U2F specifications (code for this has not yet been pushed), which reads a bitstring from the extension with OID 1.3.6.1.4.1.45724.2.1.1.

**Comment by moreati** [comment]
If you want to include this in 4.0.0, or wait for a future release/refinement of the return type then I'm fine either way.

**Comment by dainnilsson** [comment]
I went in and cherry-picked the commit, hope you don't mind (but let me know if you do)! I think getting rid of pyasn1 is worth doing now. I'd like to improve the API around this, but I don't know when I'll have time to get to it and I don't want to hold the 4.0 release back because of it.

**Comment by moreati** [comment]
Sounds good
