### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by mark-adams** [Yubico/python-u2flib-server#22]
Any way we can get a new version released to PyPI with the cryptography support?

I'd even take a pre-release version :-)

**Comment by mark-adams** [comment]
@dainnilsson This is mostly so we can begin using python-u2flib-server in our product. Installing directly from the repo doesn't work well because of the yubicommon submodules.

**Comment by dainnilsson** [comment]
Just for you: https://pypi.python.org/pypi/python-u2flib-server/4.0.0a0

Once we have Python 3 support we'll probably do the final release!

**Comment by mark-adams** [comment]
Awesome!! Thanks @dainnilsson!

**Comment by dainnilsson** [comment]
Heads up! There's a bug in the signature verification for U2F registrations in that build, here's a fixed one: https://pypi.python.org/pypi/python-u2flib-server/4.0.0a1

**Comment by dainnilsson** [comment]
Ugh... Spoke too soon. The same bug is in authentication. I'll have a new build that fixes that tomorrow.

**Comment by dainnilsson** [comment]
Ok, this one looks better: https://pypi.python.org/pypi/python-u2flib-server/4.0.0a2
Let me know if you run into any problems!

**Comment by mark-adams** [comment]
@dainnilsson Thanks!!
