### ISSUE TITLE
Tests are broken on TravisCI under PyPy

### ISSUE THREAD

**Issue by moreati** [Yubico/python-u2flib-server#24]
TravisCI has PyPy 2.5.0 installed. As of python-u2flib-server 4.0.0 we will depend on Cryptography 1.2+, which in turn requires PyPy 2.6.0+. So even if our code is bug free TravisCI reports failure - since it can't install the dependencies, e.g. https://travis-ci.org/moreati/python-u2flib-server/jobs/111979422.

The Cryptography project gets around this by using [pyenv](https://github.com/yyuu/pyenv) to install a more recent version of PyPy. e.g. https://github.com/pyca/cryptography/blob/master/.travis/.

We could do the same, or wait for TravisCI to upgrade

**Comment by dainnilsson** [comment]
While testing on PyPy would be nice, I'm not sure if it's worth jumping through all the hoops that cryptography has to do. Then again, maybe it's just a matter of copying their scripts unchanged. I'm leaning more towards removing the PyPy test for now to make the build pass, and add an issue to re-enable it once TravisCI upgrades. However, I'm not opposed to the Cryptography solution, so if you (or anyone else) wants tests to run on PyPy sooner then I'll accept a PR.

**Comment by moreati** [comment]
> I'm leaning more towards removing the PyPy test for now to make the build pass, and add an issue to re-enable it once TravisCI upgrades.

I'm happy with that

**Comment by moreati** [comment]
Note that we can still test PyPy locally, using Tox - and I do.
