### ISSUE TITLE
InvalidSignature verifying register / auth requests on Mac OS X

### ISSUE THREAD

**Issue by zollman** [Yubico/python-u2flib-server#27]
Documenting for future folks who have this same problem.

The default OS X install of OpenSSL is 0.9.8, which has some issues with the ECDSA functions (see issue #14 ). 

This manifests as Exception: `InvalidSignature` when calling `complete_register`, which is a huge pain in the neck to debug.

You can test if this is likely the reason for InvalidSignature errors with: 

``` python
import cryptography.hazmat.backends

multi_backend=cryptography.hazmat.backends.default_backend()
ossl_be=multi_backend._backends[1]
print ossl_be.openssl_version_text()
```

If that prints 0.9.8, you're going to have this problem.

When installing python-u2flib-server, use 

``` sh
env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" python setup.py install
```

Or:

``` sh
brew install libffi
brew install hidapi
brew install openssl
pip install cython

env LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include" pip install python-u2flib-server
```

Maintainers, I haven't verified the whole series of install steps on OS X with a clean install, though I recall that cython (for `chid.pxd` errors) and hidapi were helpful in my testing. Before I burn a few hours writing a PR against the docs for OS X / spend time on test case writing during setup.py to figure out if the openssl version is solid, is there demand for such a thing?

**Comment by dainnilsson** [comment]
Not sure about the demand, but I wouldn't be opposed to merging a PR for improved OSX docs or OpenSSL version checking in setup.py.
