### ISSUE TITLE
Dependencies required (but not installed/documented)?

### ISSUE THREAD

**Issue by minisu** [Yubico/python-u2flib-server#3]
It seems that these dependencies are required, but not installed/documented:
- python-webob (by the wsgi server)
- swig (by the dependency M2Crypto).

**Comment by tkam** [comment]
Hi,how can swig be installed for windows server?i have searched endlessly i cant get a result for windows server,but for linux works like a charm.

**Comment by dainnilsson** [comment]
Have you tried the Windows installer for Swig (http://www.swig.org/Doc1.3/Windows.html)? Swig is only required for building M2Crypto, which is the dependency required by this project. It's probably easier to just install a pre-built M2Crypto binary. You can get one from here: http://chandlerproject.org/Projects/MeTooCrypto#Downloads
