### ISSUE TITLE
Broken tests?

### ISSUE THREAD

**Issue by FedericoCeratto** [Yubico/python-u2flib-server#33]
What is the right way to run the tests?

nosetest (using py2) leads to:
    from .soft_u2f_v2 import SoftU2FDevice
ValueError: Attempted relative import in non-package

`python setup.py test` fails with:

...
File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = **import**('.'.join(parts_copy))`
File "/usr/lib/python2.7/test/regrtest.py", line 184, in <module>
   for module in sys.modules.itervalues():
RuntimeError: dictionary changed size during iteration

**Comment by dainnilsson** [comment]
That's strange, it works for me (using `python setup.py test`, both for python 2 and 3). Which version of python 2 are you running? Are you running the tests from master?
