### ISSUE TITLE
Exception on demo site

### ISSUE THREAD

**Issue by samee** [Yubico/python-u2flib-server#34]
I just tried out a yubikey device on this demo site: https://demo.yubico.com/u2f?tab=register

Registration failed with this error:  
Traceback (most recent call last):
  File "/root/python-u2flib-server-demo/examples/yubiauth_server.py", line 161, in **call**
    raise Exception("FIDO Client error: %s" % error)
Exception: FIDO Client error: 1 (OTHER ERROR)

It shouldn't raise an exception for any client input, right? Let me know if this is the right place for the bug. I'm using Chromium on Lubuntu 16.04, if that helps.

**Comment by rstory** [comment]
I had the same thing on Fedora.. found the solution (udev rules) here: https://forum.yubico.com/viewtopic.php?p=5938#p5938

**Comment by drbeco** [comment]
> I had the same thing on Fedora.. found the solution (udev rules) here: https://forum.yubico.com/viewtopic.php?p=5938#p5938

This link is broken. I know the issue is closed, but still may be a good pointer for who comes with the same problem and google to here. Thanks.

**Comment by emlun** [comment]
Thanks @drbeco. Unbroken link: https://forum.yubico.com/viewtopic4e66.html?p=5938#p5938
