### ISSUE TITLE
cannot use symlinks in git on windows

### ISSUE THREAD

**Issue by shuffle2** [Yubico/python-u2flib-server#36]
if you want people to be able to use your code on windows, please do not commit symlinks to git. there is not good solution for windows users.

**Comment by dainnilsson** [comment]
The symlink for the vendored code will be removed in the next release. Note that this is only an issue when working with the git repository, not when using the pre-built package, as the symlink is converted to a normal directory for that.

**Comment by dainnilsson** [comment]
The offending symlink has been removed in master.
