### ISSUE TITLE
TypeError: Object of type 'bytes' is not JSON serializable (encoding raw_response.user_presence)

### ISSUE THREAD

**Issue by shuffle2** [Yubico/python-u2flib-server#37]
uf2_v2.py's `verify_authenticate` returns `raw_response.user_presence`, which will then be passed to `json.dumps` as the touch value. This fails on py3 as the input type is `bytes`. I'm unsure why it appears to work in the instructions (additionally, the instructions show it as a raw unicode character, which seems undesirable). This value should just be converted to an integer before passing to `json.dumps`.

**Comment by dainnilsson** [comment]
The Python 3 support was an external contribution and unfortunately the library hasn't been tested thoroughly enough on Python 3. The next major version will be fully supported and tested on Python 3, and this specific issue handled in a better way.

**Comment by dainnilsson** [comment]
Python support in soon-to-be-released v5 is much improved, and these issues are fixed in it.
