### ISSUE TITLE
Demo site: "FIDO Client error: 1 (OTHER ERROR)"

### ISSUE THREAD

**Issue by damonmaria** [Yubico/python-u2flib-server#39]
I have just purchased 2 Yubikey NEOs. I was able to register them with Google but am now having trouble. When I try and use the demo site https://demo.yubico.com/u2f?tab=register I get the following:
```
 Traceback (most recent call last):
  File "/root/python-u2flib-server-demo/examples/yubiauth_server.py", line 161, in __call__
    raise Exception("FIDO Client error: %s" % error)
Exception: FIDO Client error: 1 (OTHER ERROR)
```

Same for both keys. Have restarted Chrome and rebooted.

Chrome Version 56.0.2924.87 (64-bit)
MacOS 10.12.3

**Comment by dainnilsson** [comment]
Please contact support for support issues. Off the top of my head, try disabling any extensions you have activated in Chrome, it's possible one of them is interfering with U2F.

**Comment by damonmaria** [comment]
Apologies. I had seen another Github issue for this project dealing with the same error on Ubuntu.
